sources:
  - name: airbnb
    catalog: workspace
    schema: raw
    tables:
      - name: listings
        identifier: listings

      - name: hosts
        identifier: hosts

      - name: reviews
        identifier: reviews
        config:
          loaded_at_field: date
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 24, period: hour}