FROM python:3.10-slim

# Create the home directory
RUN mkdir -p /opt/dagster/dagster_home

# Install dependencies
RUN pip install dagster dagster-webserver dagster-postgres

# Set the workdir
WORKDIR /opt/dagster/app

# Copy your code
COPY . .

# Set environment variable inside the image too
ENV DAGSTER_HOME=/opt/dagster/dagster_home