models:
  - name: dim_listings
    columns:

     - name: listing_id
       data_tests:
         - unique
         - not_null

     - name: host_id
       data_tests:
         - not_null
         - relationships:
             arguments:
               to: ref('dim_hosts')
               field: host_id

     - name: room_type
       data_tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel room']